{
 "title": "VMware vSphere  - Overview",
 "description": "VMware vSphere Dashboard (Grafana 11.x / Telegraf v1.3 / Victoriametrics 1.90)",
 "tags": [
  "VMware",
  "vSphere Overview",
  "vSphere Telegraf",
  "Prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "vcenter", "label": "vCenter Server", "query": { "query": "label_values(vcenter)" } },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": {
     "query": "label_values({vcenter=~\"$vcenter\"},clustername)"
    }
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": {
     "query": "label_values({vcenter=~\"$vcenter\", clustername=~\"$clustername\"},esxhostname)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values({vcenter=~\"$vcenter\"},dsname)"
    }
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": {
     "query": "label_values({vcenter=~\"$vcenter\", clustername=~\"$clustername\", esxhostname=~\"$esxi\"},vmname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Datacenter Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vSphere Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (vcenter) (vsphere_host_sys_uptime_latest{vcenter=~\"$vcenter\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by (clustername) (vsphere_host_sys_uptime_latest{vcenter=~\"$vcenter\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (esxihostname) (vsphere_host_sys_uptime_latest{vcenter=~\"$vcenter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by (vmname) (vsphere_vm_cpu_used_summation{vcenter=~\"$vcenter\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by (dsname) (vsphere_datastore_disk_capacity_latest{vcenter=~\"$vcenter\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$clustername Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "repeat": "clustername",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vsphere_host_mem_usage_average{vcenter=~\"$vcenter\", clustername=~\"$clustername\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(vsphere_host_cpu_usage_average{vcenter=~\"$vcenter\", clustername=~\"$clustername\", cpu=\"instance-total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overprovisioned", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$esxi Overprovisioned - CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "repeat": "esxi",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cpu) (vsphere_host_cpu_usage_average{esxhostname=~\"$esxi\", cpu!=\"instance-total\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by (cpu,vmname) (vsphere_vm_cpu_used_summation{esxhostname=~\"$esxi\", cpu!=\"instance-total\"}))",
     "legendFormat": "__auto"
    },
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "$esxi Overprovisioned - RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "repeat": "esxi",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time (vsphere_host_mem_totalCapacity_average{esxhostname=~\"$esxi\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vsphere_vm_mem_entitlement_average{esxhostname=~\"$esxi\"})",
     "legendFormat": "__auto"
    },
    { "expression": "$E/($D*1024)", "type": "math" }
   ]
  },
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Cluster CPU Usage %  [$clustername]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vsphere_host_cpu_usage_average{clustername=~\"$clustername\", cpu=\"instance-total\"}",
     "legendFormat": "{{esxhostname}} CPU Usage"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage in % [$clustername]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vsphere_host_mem_usage_average{clustername=~\"$clustername\"}",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "(sum(vsphere_host_net_bytesTx_average{clustername=~\"$clustername\",interface=\"instance-total\"}) by (esxhostname))*-1",
     "legendFormat": "{{esxhostname}} - TX"
    },
    {
     "expr": "(sum(vsphere_host_net_bytesRx_average{clustername=~\"$clustername\",interface=\"instance-total\"}) by (esxhostname))",
     "legendFormat": "{{esxhostname}} RX"
    }
   ]
  },
  {
   "title": "Cluster Storage Adapter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum (vsphere_host_storageAdapter_commandsAveraged_average{clustername=~\"$clustername\"}) by (esxhostname)",
     "legendFormat": "{{esxhostname}} - IOPS"
    }
   ]
  },
  {
   "title": "Cluster Storage Adapter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(vsphere_host_storageAdapter_totalReadLatency_average{clustername=~\"$clustername\"}) by (esxhostname)",
     "legendFormat": "{{esxhostname}} - Read"
    },
    {
     "expr": "avg(vsphere_host_storageAdapter_totalWriteLatency_average{clustername=~\"$clustername\"}) by (esxhostname)",
     "legendFormat": "{{esxhostname}} - Write"
    }
   ]
  },
  { "title": "Datastore Usage - Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$datastore",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "repeat": "datastore",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_datastore_disk_used_latest{dsname=~\"$datastore\"}/vsphere_datastore_disk_capacity_latest{dsname=~\"$datastore\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hypervisor Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Hypervisor CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vsphere_host_cpu_usage_average{esxhostname=~\"$esxi\",cpu=\"instance-total\"}",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Hypervisor Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vsphere_host_mem_usage_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Hypervisor Net Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(vsphere_host_net_usage_average{esxhostname=~\"$esxi\"}) by (esxhostname)",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  { "title": "Virtual Machine Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Virtual Machine CPU Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vsphere_vm_cpu_usage_average{vmname=~\"$virtualmachine\",cpu=\"instance-total\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Memory Usage Avg.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vsphere_vm_mem_usage_average{vmname=~\"$virtualmachine\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Virtual Machine CPU READY ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vsphere_vm_cpu_ready_summation{vmname=~\"$virtualmachine\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Network Usage Avg (Kbps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vsphere_vm_net_usage_average{vmname=~\"$virtualmachine\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Read VMFS Block IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vsphere_vm_virtualDisk_numberReadAveraged_average{vmname=~\"$virtualmachine\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Write VMFS Block IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vsphere_vm_virtualDisk_numberWriteAveraged_average{vmname=~\"$virtualmachine\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Block Latency Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vsphere_vm_virtualDisk_totalReadLatency_average{vmname=~\"$virtualmachine\"}",
     "legendFormat": "{{vmname}} Read"
    },
    {
     "expr": "vsphere_vm_virtualDisk_totalWriteLatency_average{vmname=~\"$virtualmachine\"}",
     "legendFormat": "{{vmname}} Read"
    }
   ]
  }
 ]
}