{
 "title": "VMware vSphere  - Hosts",
 "description": "VMware vSphere Dashboard - Hosts (Grafana 11.x / Telegraf v1.3 / Victoriametrics 1.90)",
 "tags": [
  "VMware",
  "vSphere Telegraf",
  "Prometheus",
  "vSphere Hosts"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "vcenter", "label": "vCenter Server", "query": { "query": "label_values(vcenter)" } },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": {
     "query": "label_values({vcenter=~\"$vcenter\"},clustername)"
    }
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": {
     "query": "label_values({vcenter=~\"$vcenter\", clustername=~\"$clustername\"},esxhostname)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values({vcenter=~\"$vcenter\", esxhostname=~\"$esxi\"},dsname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$esxi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "esxi" },
  {
   "title": "ESXi VM Quick Overview",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_host_cpu_usagemhz_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vsphere_host_mem_usage_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vsphere_host_cpu_usage_average{esxhostname=~\"$esxi\", cpu=\"instance-total\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vsphere_host_sys_uptime_latest{esxhostname=~\"$esxi\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vsphere_host_mem_totalCapacity_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization Avg %",
   "type": "timeseries",
   "description": "CPU usage as a percentage during the interval.",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(vsphere_host_cpu_usage_average{esxhostname=~\"$esxi\"}\n) by (esxhostname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vsphere_host_mem_usage_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Ready in miliseconds",
   "type": "timeseries",
   "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vsphere_host_cpu_ready_summation{esxhostname=~\"$esxi\"}/1000",
     "legendFormat": "CPU Total"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "Network utilization (combined transmit-rates and receive-rates) during the interval.",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vsphere_host_net_bytesTx_average{esxhostname=~\"$esxi\"}*-1",
     "legendFormat": "{{interface}} - TX"
    },
    {
     "expr": "vsphere_host_net_bytesRx_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "{{interface}} - RX"
    }
   ]
  },
  {
   "title": "Total Disk Latency",
   "type": "timeseries",
   "description": "The average time a read, or write, from the virtual disk takes.",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vsphere_host_disk_totalWriteLatency_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "{{disk}} - Write"
    },
    {
     "expr": "vsphere_host_disk_totalReadLatency_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "{{disk}} - Read"
    }
   ]
  },
  {
   "title": "Storage Adapter IOPS",
   "type": "timeseries",
   "description": "The average time a read, or write, from the datastore takes.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vsphere_host_storageAdapter_numberWriteAveraged_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "{{adapter}} - Write"
    },
    {
     "expr": "vsphere_host_storageAdapter_numberReadAveraged_average{esxhostname=~\"$esxi\"}",
     "legendFormat": "{{adapter}} - Read"
    }
   ]
  }
 ]
}